#!/bin/bash
#
# trinkup - TRivial INcremental bacKUP script
#
# Уж 200 раз твердили Сене:
# Хардлинк спасет от удаленья!
# А кто создать его поможет?
# Crontab и man, тупая рожа!
#
# (c) linux.org.ru, no-dashi
#
# Licensed under DWTFYWWI license, but recommended to be used before drinkup.
#

set -e

if ! which rsync >/dev/null; then
   echo "rsync not found!" >&2
   exit 1
fi

USAGE="
usage:

    $0 <rsync_source> <backups_directory> <number_of_backups> [rsync_args]

    Keep calm and drink vodka!
"

SRC="$1"
BACKUPS="$2"
ROTATE="$3"

if [ -z "$SRC" ] || [ -z "$BACKUPS" ] || ! [ -n "$ROTATE" -a "$ROTATE" -gt 1 ] ; then
    echo -e "$USAGE" >&2
    exit 1
fi

if ! [ -d "$BACKUPS" ] ; then
    echo "'$BACKUPS' directory should exist!" >&2
    exit 1
fi

# shift rsync args to $*
shift 3

WORKDIR="$(echo "$BACKUPS/`date --iso=seconds`" | sed 's,/\+,/,g')"

echo "Destination directory: '$WORKDIR'"

if [ -n "`ls \"$BACKUPS\"`" ] ; then
    OLDEST="`ls -dr \"$BACKUPS\"/* | awk \"NR==$ROTATE\"`"
    NEWEST="`ls -dr \"$BACKUPS\"/* | awk NR==1`"
fi

# reusing of old backups improves the performance on large directories since we
# don't need to remove old backup and create all files in new backup
if [ -d "$OLDEST" ] ; then
    echo "Reusing '$OLDEST' to reduce the disk operations amount."
    mv "$OLDEST" "$WORKDIR"
fi

# the main magic thing of incremental backup is here: we don't create the
# copies of all files, but use hardlinks which point on the same file if it was
# not change between backups
if [ -d "$NEWEST" ] ; then
    echo "Syncing with '$NEWEST'..."
    cp -laf "$NEWEST/." "$WORKDIR"
fi

echo "Running rsync..."
rsync -a --delete $* "$SRC" "$WORKDIR"

echo "Done."
